baseURL = 'https://UIBreaker.github.io/DoAnLapTrinhMang/'
publishDir = "docs"
languageCode = 'vi-VN'
title = 'Blog của Nhật Nam'
theme = 'PaperMod'
author = "Nguyễn Vũ Nhật Nam"


[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  

[params.assets]
    disableFingerprinting = true
    # Giữ nguyên tên file, không cần thêm đường dẫn nào cả
    customCSS = ["custom.css"]
    customJS = ["snow.js"]


  [params.profileMode]
    enabled = true
    title = "Nguyễn Vũ Nhật Nam"
    # Slogan ngắn gọn, đúng chất sinh viên HUTECH sắp ra trường
    subtitle = "Sinh viên Năm 4 CNTT - HUTECH | Chuyên trị Java & Network"
    imageUrl = "https://github.com/UIBreaker.png"
    imageTitle = "Avatar"
    imageWidth = 120
    imageHeight = 120

    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/UIBreaker"
    
    # Thêm Facebook/Email để nhà tuyển dụng liên hệ (nếu muốn)
    # [[params.socialIcons]]
    #   name = "email"
    #   url = "mailto:nam@example.com"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang Chủ"
    url = "/"
    weight = 10
  
  # --- THÊM MENU GIỚI THIỆU Ở ĐÂY ---
  [[menu.main]]
    identifier = "about"
    name = "Giới thiệu" # Nút này sẽ dẫn vào bài viết chi tiết
    url = "/about"
    weight = 15

  [[menu.main]]
    identifier = "blog"
    name = "Bài Viết"
    url = "/posts"
    weight = 20