baseURL = 'https://UIBreaker.github.io/DoAnLapTrinhMang/'
publishDir = "docs"
languageCode = 'vi-VN'
title = 'Blog của Nhật Nam' # Đã sửa cho cá nhân hóa hơn
theme = 'PaperMod'
author = "Nguyễn Vũ Nhật Nam" # Thêm metadata tác giả

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true # Hiện bài trước/sau
  ShowBreadCrumbs = true  # Hiện đường dẫn điều hướng
  ShowCodeCopyButtons = true # Nút copy code (Rất cần cho blog lập trình!)
  ShowToc = true # Hiện mục lục bài viết

  # --- FIX LỖI GIAO DIỆN (GIỮ NGUYÊN) ---
  [params.assets]
    disableFingerprinting = true
  # --------------------------------------

  [params.profileMode]
    enabled = true
    title = "Nguyễn Vũ Nhật Nam" # Đã cập nhật tên chính chủ
    subtitle = "Sinh viên KTPM | Đam mê Lập trình Mạng & Java" # Trau chuốt lại slogan chút cho hay
    imageUrl = "https://github.com/UIBreaker.png" # Tự động lấy avatar từ GitHub của bạn (Nhìn rất Pro!)
    imageTitle = "Avatar"
    imageWidth = 120
    imageHeight = 120

    # Dùng Social Icons nhìn sẽ tinh tế hơn nút bấm to
    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/UIBreaker"
    
    # Bạn có thể thêm Facebook hoặc Email nếu thích (Bỏ dấu # để mở)
    # [[params.socialIcons]]
    #   name = "facebook"
    #   url = "https://facebook.com/link-cua-ban"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang Chủ" # Việt hóa menu
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "blog"
    name = "Bài Viết" # Việt hóa menu
    url = "/posts"
    weight = 20