baseURL = 'https://UIBreaker.github.io/DoAnLapTrinhMang/'
publishDir = "docs"
languageCode = 'vi-VN'
title = 'Blog Lập Trình Của Tôi'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true

  # --- ĐOẠN MỚI THÊM ĐỂ SỬA LỖI ---
  [params.assets]
    disableFingerprinting = true
  # --------------------------------

  [params.profileMode]
    enabled = true
    title = "Nguyễn Văn A" # Nhớ sửa tên bạn ở đây luôn nhé!
    subtitle = "Sinh viên đam mê Lập trình Mạng & Java"
    
    [[params.profileMode.buttons]]
      name = "GitHub"
      url = "https://github.com/UIBreaker"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
    weight = 20